language: generic
sudo: false
dist: precise

env:
    global:
    - BYOND_MAJOR="513"
    - BYOND_MINOR="1511"
    - DM_BUILDFILE="IS12Warfare.dme"
    - SPACEMAN_DMM_VERSION=suite-1.4

matrix:
  include:
    - name: "Compile"
      addons:
        apt:
          packages:
            - libc6-i386
            - libgcc1:i386
            - libstdc++6:i386
      cache:
        directories:
            - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
      install:
        - chmod +x ./install-byond.sh
        - ./install-byond.sh
      script:
        - (! grep -rn 'step_[xy]' maps)
        - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
        - bash dm.sh ${DM_BUILDFILE}
